alias art='php artisan'
alias subl='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
alias chrome='open -a Google\ Chrome\ Canary'
alias ff='open -a FirefoxDeveloperEdition'
alias pbcopyt='reattach-to-user-namespace pbcopy'
alias vi="vim"
alias pg_start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg_stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias redis_start='redis-server /usr/local/etc/redis.conf'

alias ber="bundle exec rails "
alias bera="bundle exec rake "
alias be="bundle exec "

alias alg="alias | grep "
alias vmap="cat ~/.vimrc | grep map "
alias gitfuckit="git checkout -- ."

alias gcop="git checkout \$(git branch | cut -c 3- | pick)"
alias cdp="cd \$(find . -type d | pick)"
alias kp="kill \$(ps -e | awk '{if(NR!=1) { print \$4, \$1 }}' | pick -do | tail -n +2)"
alias vimw="vim \$(ag -l WORD | pick)"
alias vimf="vim \$(find * | pick)"
alias rakep="rake \$(rake -T | cut -f2 -d' ' | pick)"
alias histp="\$(history | cut -c8- | sort -u | pick)"
alias pjson='python -m json.tool'
